# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xai7odx7jQENI1SxYY2oQDljVf7Zz6PU
"""

# Quydagi dastur orqali ikki sonning o'zaro teng ekanini tekshirish dasturi
num1=float(input("Birinchi raqamni kiriting:"))
num2=float(input("Ikkinchi raqamni kiriting:"))

#Ular teng bo'lsa To'g'ri!,agar teng bo'lmasa Noto'g'ri!yozuvi chiqishi kerak
if num1==num2:
     print("To'g'ri")
else:
     print("Noto'g'ri")